export const pdfFiles = [
  { id: '1TJj5honFOdixxtO1if2kdwPLOHPf1vLC', title: 'A, An or The?' },
  { id: '1TOnxAIZcXN7PJYpt4JEOxYwPSYXxIE53', title: 'Action Verbs - Matching' },
  { id: '1voQ518TgsDfbFSN2GP8oel_20DeLLgef', title: 'Actions Crossword 1' },
  { id: '1-twsnFvkVq6V7q-_Lc6pN2c42KsglXX1', title: 'Actions Crossword 2' },
  { id: '1Z_2sqY-VOeSOXT6aORGAflozeMaYbVT3', title: 'Actions Crossword 3' },
  { id: '1jSzbfNnaUImnZw6Yc5F6KMuOBMS-S6Nh', title: 'Adjectives Crossword' },
  { id: '1rFSkGCzl7BvfRF4z44HtxG4TnD9CTlt2', title: 'Alfred`s Daily Routine' },
  { id: '13ffHiGq915k8x1WQyDU9uVXj4F5DfPv5', title: 'Animals - Can' },
  { id: '1fFsW0U3rtbr0BZWhNRKVgyrA94iWit2N', title: 'Animals - Crossword' },
  { id: '12UJqCh0Eq0nmUgsBUgjDu_QRrA1CEYDG', title: 'Big Animal - Crossword' },
  { id: '1CBwG0B75MxgGu4J6ynZMYdV6MRriZC8F', title: 'Body Parts - Crossword' },
  { id: '1Mc_cnWRcyzk1jg-0J6N5jthPqza4csH2', title: 'Big Body - Crossword' },
  { id: '1JGbLk3iZFK9rEzk0UOQrDd0UAxJUHkQp', title: 'Colors - Crossword' },
  { id: '1ghye4Hpz9xcyrdLgWumVXRA_2Ba7pYgU', title: 'Connectors - and, but, so' },
  { id: '1ZY059iUCWN6mZtA4MgC6YmkgwJdjyRpR', title: 'Describe Animals (Adjectives)' },
  { id: '1nrCenlRdrHtStVtXZmy4_dwYCPCopZw0', title: 'Feelings and Emotions' },
  { id: '1ClpXgXDJU2EGQumw8YLtmMprLsS67j0m', title: 'Feelings (Faces)' },
  { id: '16GjOxjPAcpdIvNWm6JM4HedLZMnKxawe', title: 'Feelings (Multiple Choice)' },
  { id: '16ZEY3eySm0ITeQo96XzBpfHXqwCCScUK', title: 'Food Crossword' },
  { id: '1Xn6FTx2eVPJ1d9iGAKLpbovtjLv4zQrG', title: 'Fruits Crossword' },
  { id: '1voFXyfhdVtYBClu9J0M6l_Un6E--n23U', title: 'Giving Advice (Should)' },
  { id: '1nA71vHB8QNa4s_DJoNbaHuO4n37gAjPG', title: 'Introduce myself' },
  { id: '1PXUUCZqAZbeI9R8UyfXC8yGWzCM2zoXF', title: 'Sentence Structure 1' },
  { id: '1QI3Gy_yYoj5izRCkWRJJO13A2pZYRZHt', title: 'Sentence Structure 2' },
  { id: '18gfQ23IsgV4ffbblewUbXIyCKxS2O9fL', title: 'Should - Shouldn`t' },
  { id: '1wi1sIowfnnXK7StVaHBXsJuDlZ5t12GD', title: 'What is she/he doing?' },
  { id: '1HSZv1sL5l-90cIchoe7CU8ePkQRD-2TP', title: 'Wild Animals (WordSearch)' },
]
